name: Create Jira issue # 1
on: # 2
    issues:
        types: [opened]

jobs: # 3
    create-issue: # 4
        name: Create Jira issue # 5
        runs-on: ubuntu-latest # 6
        steps: # 7
            - name: Extract Jira Ticket Number
              id: extract_ticket_number
              run: echo "::set-output name=ticket_number::$(echo ${{ github.event.issue.title }} | grep -oE 'QIHI-[0-9]+')"

            - name: Check if Jira Ticket Number exists
              if: steps.extract_ticket_number.outputs.ticket_number != ''
              run: exit 1

            - name: Login
              uses: atlassian/gajira-login@v3 # 8
              env:
                  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }} # 9
                  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

            - name: Create Issue
              uses: atlassian/gajira-create@v3
              with:
                  project: QIHI # 10 - 프로젝트 key
                  issuetype: Task # 11 - 이슈 타입
                  summary: '${{ github.event.issue.title }}'
                  description: '${{ github.event.issue.html_url }}'
